name: Update Mob Heads

on:
  push:
    branches: ["master"]

  # Allow running workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate head previews
        run: python3 scripts/generate_head_overview.py

      - name: Add new files and commit
        uses: EndBug/add-and-commit@v9.0.1
        with:
          author_name: Rodney_Mc_Kay
          author_email: 36546810+RodneyMKay@users.noreply.github.com
          message: Update Mob Heads
